#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Rebb.App.Client.Resource", IsApplication=true)]

namespace Rebb.App.Client
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int activity_horizontal_margin = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int activity_vertical_margin = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int fab_margin = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int nav_header_height = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int nav_header_vertical_spacing = 2130837508;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int button_background = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int gradient_primary_dark = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ic_menu_camera = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ic_menu_gallery = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int ic_menu_manage = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int ic_menu_send = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int ic_menu_share = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int ic_menu_slideshow = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int side_nav_bar = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int start_background = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int tread_name = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int tread_white = 2130903051;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Font
		{
			
			// aapt resource value: 0x7F040000
			public const int montserrat = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int montserrat_black = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int montserrat_blackitalic = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int montserrat_bold = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int montserrat_bolditalic = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int montserrat_extrabold = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int montserrat_extrabolditalic = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int montserrat_extralight = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int montserrat_extralightitalicc = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int montserrat_italic = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int montserrat_light = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int montserrat_lightitalic = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int montserrat_medium = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int montserrat_mediumitalic = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int montserrat_regular = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int montserrat_semibold = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int montserrat_semibolditalic = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int montserrat_thin = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int montserrat_thinitalic = 2130968594;
			
			static Font()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Font()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int action_settings = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int btnStartRegister = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int chk1 = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int drawer_layout = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int fab = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int imageView = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int nav_camera = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int nav_gallery = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int nav_manage = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int nav_send = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int nav_share = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int nav_slideshow = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int nav_view = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int textView = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int toolbar = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int activity_main = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_bar_main = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int content_main = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int nav_header_main = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int register_account = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int splash_screen = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int start_activity = 2131099654;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F070000
			public const int activity_main_drawer = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int menu_main = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F080000
			public const int ic_launcher = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int ic_launcher_foreground = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int ic_launcher_round = 2131230722;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int action_settings = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int hint_acceptterms = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int hint_confirmpassword = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int hint_email = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int hint_password = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int navigation_drawer_close = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int navigation_drawer_open = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int register_account_text = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int register_text = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int start_text = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int start_title = 2131296267;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int AppTheme = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int AppTheme_AppBarOverlay = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int AppTheme_NoActionBar = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int AppTheme_PopupOverlay = 2131361795;
			
			// aapt resource value: 0x7F0A0005
			public const int button_primary = 2131361797;
			
			// aapt resource value: 0x7F0A0004
			public const int CardView_EditLayout = 2131361796;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
